module.exports = {
  AUDIO_DATA: 2,
  AUDIO_END: 10,
  AUDIO_START_REQ: 8,
  AUDIO_START_RESP: 9,
  DECODER_CONTROL_REQ: 14,
  DEVICE_CONTROL_REQ: 250,
  FETCH_BATTERY_POWER_REQ: 251,
  FETCH_BATTERY_POWER_RESP: 252,
  HEAD_LEN: 23,
  KEEP_ALIVE: 255,
  LOGIN_REQ: 0,
  LOGIN_RESP: 1,
  MEDIA_LOGIN_REQ: 0,
  TALK_DATA: 3,
  TALK_END: 13,
  TALK_START_REQ: 11,
  TALK_START_RESP: 12,
  VERIFY_REQ: 2,
  VERIFY_RESP: 3,
  VIDEO_DATA: 1,
  VIDEO_END: 6,
  VIDEO_FRAMEINTERVAL: 7,
  VIDEO_START_REQ: 4,
  VIDEO_START_RESP: 5,

  headers: {
    video: "MO_V",
    control: "MO_O"
  }
};